name: build-docker-image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag (e.g. 2.1)'
        required: true
        type: string

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    environment: Docker
    env:
      IMAGE: yelfive/nextcloud:${{ inputs.image_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Prepare
        run: |
          sed -i "s/LSKY_VERSION_CHANGE_ME/$LSKY_VERSION/g" Dockerfile
          cat Dockerfile

      - name: Build docker image
        run: |
          docker build -t ${IMAGE} .

      - name: List docker image
        run: docker image ls

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        run: |
          docker push ${IMAGE}
