name: build-docker-image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag (e.g. 2.1)'
        required: true
        type: string

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    environment: DockerHub
    env:
      IMAGE: yelfive/nextcloud:${{ inputs.image_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Prepare
        run: |
          sed -i "s/LSKY_VERSION_CHANGE_ME/$LSKY_VERSION/g" Dockerfile
          cat Dockerfile

      - name: Build docker image
        run: |
          docker build -t ${IMAGE} .

      - name: List docker image
        run: docker image ls

      - name: DockerHub> login 
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --password-stdin -u ${{ secrets.DOCKERHUB_USER }}

      - name: DockerHub> push
        run: docker push ${IMAGE}

      - name: DockerHub> logout
        run: docker logout
